server:
  port: 8080
  servlet:
    context-path: /firebase

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/firebase"
    username: postgres
    password: csuitk15
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "cq9rJup0g+aG3M+mbgXGLi4JW9SMO0ZJbtm2IwKSTNRFmFOXLqo5+gXrmEhJZb3/"